// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1726821296);
user_pref("app.update.lastUpdateTime.background-update-timer", 1726821296);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1723825367);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1723825126);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1726821296);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1724228717);
user_pref("browser.laterrun.bookkeeping.sessionCount", 11);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20240321223417");
user_pref("browser.startup.homepage_override.mstone", "115.9.1");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20240809043541");
user_pref("extensions.lastAppVersion", "7.0");
user_pref("extensions.lastPlatformVersion", "115.9.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"zotero-plugin@inciteful.xyz\":\"af50a234-65f7-45ba-8951-6995a1273770\",\"better-bibtex@iris-advies.com\":\"bee2eca9-c9df-41bd-9b21-41543929e920\"}");
user_pref("extensions.zotero.dataDir", "/home/manuelbb/Zotero");
user_pref("extensions.zotero.export.bibliographySettings", "{\"mode\":\"bibliography\",\"method\":\"copy-to-clipboard\"}");
user_pref("extensions.zotero.export.lastLocale", "en-US");
user_pref("extensions.zotero.export.lastStyle", "http://www.zotero.org/styles/ieee");
user_pref("extensions.zotero.export.lastTranslator", "ca65189f-8815-4afe-8c8b-8c7c15f0edca");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":false,\"exportFileData\":false,\"useJournalAbbreviation\":false,\"keepUpdated\":false,\"worker\":true,\"includeAnnotations\":false}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.firstRunGuidanceShown.z7Banner", false);
user_pref("extensions.zotero.hiddenNotices", "{\"crossref-outage-2024-08-21\":1724318548}");
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-general");
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.lastWebDAVOrphanPurge", 1726821291);
user_pref("extensions.zotero.newItemTypeMRU", "journalArticle,thesis,computerProgram");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-collections-pane\":{\"width\":\"207\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"583\",\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"open\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.better-bibtex-iris-advies-com-betterbibtex-section-citationkey.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 12);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"C10\",\"sessionID\":\"8yhd5LUM\"},{\"id\":\"L1\",\"sessionID\":\"fmAPAKG0\"},{\"id\":\"L1\",\"sessionID\":\"dchD5zgu\"}]");
user_pref("extensions.zotero.sync.server.username", "manuelbb");
user_pref("extensions.zotero.sync.storage.protocol", "webdav");
user_pref("extensions.zotero.sync.storage.url", "uni-paderborn.sciebo.de/remote.php/webdav");
user_pref("extensions.zotero.sync.storage.username", "manuelbb@uni-paderborn.de");
user_pref("extensions.zotero.sync.storage.verified", true);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/home/manuelbb/.nix-profile/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.translators.better-bibtex.skipFields", "file");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.skipInstallation", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1726821399);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1723825189);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1726821399616");
user_pref("security.sandbox.content.tempDirSuffix", "e6387807-3427-4d78-8e74-b87e7cfc7df1");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.content-prefs.sqlite", 1724315372);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1725891010);
