// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20240304070404");
user_pref("extensions.lastAppVersion", "6.0.35");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.dataDir", "/home/manuelbb/Zotero");
user_pref("extensions.zotero.export.lastTranslator", "f895aa0d-f28e-47fe-b247-2ea77c6ed583");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":false,\"exportFileData\":false,\"useJournalAbbreviation\":false,\"biblatexAPA\":false,\"biblatexChicago\":false,\"keepUpdated\":false,\"worker\":false,\"includeAnnotations\":false}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.lastViewedFolder", "C2");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-collections-pane\":{},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 6);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/home/manuelbb/.nix-profile/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.skipInstallation", true);
user_pref("gecko.handlerService.migrated", true);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
